import {crops,calculate,tree} from './data.js';
import {entries,save} from './storage.js';
const screen=document.querySelector('#screen'),message=document.querySelector('#message');
let tab='calculator',path=['start'],selectedCrop='maize',syncing=false,installPrompt;
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=()=>crops.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');
function tell(text){message.textContent=text;}
function connection(){document.querySelector('#connection').textContent=navigator.onLine?'● Online · sync available':'○ Offline · tools ready';}
async function render(){
 document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 if(tab==='calculator'){
 screen.innerHTML=`<article><h2>Plan your inputs</h2><p class="muted">Explore a sample input quantity. Field size is in hectares (1 ha = 10,000 m²).</p><form id="calc"><div class="grid"><div><label for="crop">Crop</label><select id="crop">${options()}</select></div><div><label for="area">Field size (ha)</label><input id="area" type="number" min="0.0001" max="100000" step="any" value="1" required></div></div><div class="actions"><button class="primary">Calculate sample quantity</button></div></form><div id="result" aria-live="polite"></div></article>`;
 document.querySelector('#calc').onsubmit=e=>{e.preventDefault();try{const crop=crops.find(c=>c.id===document.querySelector('#crop').value),area=Number(document.querySelector('#area').value);document.querySelector('#result').innerHTML=`<div class="result"><div class="number">${calculate(crop.rate,area).toLocaleString(undefined,{maximumFractionDigits:3})} kg</div><p>${crop.name} · ${area} ha × ${crop.rate} kg/ha</p><p class="muted">Illustrative generic input only. This is not a fertilizer or pesticide recommendation.</p></div>`;}catch(e){tell(e.message);}};
 }else if(tab==='diagnosis'){
 const node=tree[path.at(-1)];screen.innerHTML=`<article><h2>Explore crop symptoms</h2><p class="muted">A sample triage flow, not a confirmed diagnosis. Step ${path.length}.</p><label for="diagnostic-crop">Crop</label><select id="diagnostic-crop">${options()}</select><div class="result"><h3>${node.question||node.title}</h3>${node.detail?`<p>${node.detail}</p><p class="muted">Crop: ${crops.find(c=>c.id===selectedCrop).name}. This generic demo flow needs crop-specific validation.</p>`:''}</div><div class="choices">${(node.choices||[]).map(([label,next])=>`<button data-next="${next}">${label}</button>`).join('')}</div><div class="actions"><button id="back" ${path.length===1?'disabled':''}>Back</button><button id="restart">Restart</button>${node.detail?'<button id="record" class="primary">Add to logbook</button>':''}</div></article>`;
 document.querySelector('#diagnostic-crop').value=selectedCrop;document.querySelector('#diagnostic-crop').onchange=e=>{selectedCrop=e.target.value;render();};
 screen.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{path.push(b.dataset.next);render();});document.querySelector('#back').onclick=()=>{path.pop();render();};document.querySelector('#restart').onclick=()=>{path=['start'];render();};if(node.detail)document.querySelector('#record').onclick=async()=>{tab='logbook';await render();document.querySelector('#log-crop').value=selectedCrop;document.querySelector('#notes').value=`${node.title}: ${node.detail}`;};
 }else if(tab==='logbook'){
 screen.innerHTML=`<div class="grid"><article><h2>Keep a field note</h2><form id="log"><label for="log-crop">Crop</label><select id="log-crop">${options()}</select><label for="field">Field name</label><input id="field" maxlength="100" placeholder="e.g. North field" required><label for="notes">Observation</label><textarea id="notes" maxlength="2000" placeholder="What did you notice?" required></textarea><div class="actions"><button class="primary">Save on this device</button></div></form></article><article><h2>Field history</h2><button id="sync" ${syncing?'disabled':''}>${syncing?'Syncing…':'Sync now'}</button><p class="muted">Pending notes stay on this device until the demo server confirms receipt.</p><div id="history"></div></article></div>`;
 document.querySelector('#log').onsubmit=async e=>{e.preventDefault();try{await save({id:crypto.randomUUID(),crop:document.querySelector('#log-crop').value,field:document.querySelector('#field').value.trim(),notes:document.querySelector('#notes').value.trim(),createdAt:new Date().toISOString(),synced:false});tell('Saved on this device.');await render();sync();}catch(e){tell('Could not save: '+e.message);}};document.querySelector('#sync').onclick=sync;
 try{const records=await entries();if(tab!=='logbook')return;document.querySelector('#history').innerHTML=records.length?records.map(r=>`<div class="entry"><strong>${escape(r.field)}</strong> · ${escape(r.crop)}<br><span class="badge">${r.synced?'Synced':'Pending sync'}</span><p>${escape(r.notes)}</p><small>${new Date(r.createdAt).toLocaleString()}</small></div>`).join(''):'<p class="muted">Your first field note starts here.</p>';}catch(e){tell('Device storage unavailable: '+e.message);}
 }else{
 screen.innerHTML='<article><h2>Extension officer view</h2><p class="muted">Mock cloud records from this demo server. Requires a connection. No authentication: use fictional data only.</p><button id="refresh">Refresh records</button><div id="cloud"></div></article>';document.querySelector('#refresh').onclick=loadCloud;loadCloud();
 }
}
async function loadCloud(){try{const response=await fetch('/api/entries',{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error('Server unavailable');const records=await response.json();if(tab==='officer')document.querySelector('#cloud').innerHTML=records.length?records.map(r=>`<div class="entry"><strong>${escape(r.field)}</strong> · ${escape(r.crop)}<p>${escape(r.notes)}</p><small>${escape(r.createdAt)}</small></div>`).join(''):'<p>No synced records yet.</p>';}catch{if(tab==='officer')document.querySelector('#cloud').textContent='Cloud unavailable. Your local tools and notes still work.';}}
async function sync(){if(syncing||!navigator.onLine)return;syncing=true;try{for(const record of (await entries()).filter(r=>!r.synced)){const response=await fetch('/api/entries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record),signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error('Server did not accept the record');await save({...record,synced:true});}tell('All saved notes are synced.');}catch{tell('Sync paused. Notes are safe on this device; retry when connected.');}finally{syncing=false;if(tab==='logbook')await render();}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;tell('');render();});
window.addEventListener('online',()=>{connection();sync();});window.addEventListener('offline',connection);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelector('#install').hidden=false;});document.querySelector('#install').onclick=async()=>{await installPrompt.prompt();installPrompt=null;document.querySelector('#install').hidden=true;};
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{document.querySelector('#ready').textContent='Offline shell cached. On iPhone, use Share → Add to Home Screen.';}).catch(()=>{document.querySelector('#ready').textContent='Offline setup failed. Use localhost or HTTPS and reload.';});}else document.querySelector('#ready').textContent='Offline installation requires a browser with service worker support.';
connection();render();sync();setInterval(()=>{if(navigator.onLine)sync();},30000);
