import { test, expect } from '@playwright/test';
import { primary, back, assertSafeActions } from './helpers/calculator';
for(const [width,height] of [[360,640],[390,844],[768,1024],[1366,768],[360,320],[640,360]])for(const mode of ['english','pseudo','large-text'])test(`crop and farm setup ${width}x${height} ${mode}`,async({page,context})=>{
 test.setTimeout(60000);await page.setViewportSize({width,height});await page.goto(mode==='pseudo'?'/?pseudo=1':'/');if(mode==='large-text')await page.evaluate(()=>document.documentElement.style.fontSize='200%');await assertSafeActions(page);await primary(page).click();
 for(let step=0;step<4;step++){await assertSafeActions(page);await expect(page.locator('.tool-nav')).toHaveCount(0);if(step===1)for(const crop of ['maize','tomato','beans','cabbage'])await page.locator(`input[value="${crop}"]`).check();if(step===2)await page.locator('input[type="number"]').fill('2.5');await primary(page).click();}
 await expect(page.locator('.tool-nav')).toBeVisible();await page.getByRole('button',{name:/Edit farm setup/}).click();await back(page).click();await expect(page.locator('.tool-nav')).toBeVisible();await primary(page).click();
 for(const crop of ['maize','tomato','beans','cabbage']){
  await expect(page.locator('input[name="check-crop"]')).toHaveCount(4);await page.locator(`input[name="check-crop"][value="${crop}"]`).check();await assertSafeActions(page);await primary(page).click();await assertSafeActions(page);await primary(page).click();for(let question=0;question<3;question++){await page.locator('input[value="no"]').check();await assertSafeActions(page);await primary(page).click();}await expect(page.locator('.guidance-list li')).toHaveCount(4);await assertSafeActions(page);if(crop==='maize'){await primary(page).click();for(let i=0;i<4;i++){await assertSafeActions(page);await primary(page).click();}await back(page).click();}else{await expect(page.locator('h2')).not.toContainText('FAW');await primary(page).click();}
 }
 await back(page).click();await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));});await context.setOffline(true);await page.reload();await expect(page.locator('.farm-setup')).toHaveCount(0);await expect(page.locator('.tool-home')).toContainText('Beans');await primary(page).click();await page.locator('input[name="check-crop"][value="cabbage"]').check();await primary(page).click();await primary(page).click();for(let i=0;i<3;i++){await page.locator('input[value="yes"]').check();await primary(page).click();}await expect(page.locator('.guidance-list')).toContainText('adviser');await assertSafeActions(page);
});

test('AgriSmart manifest remains installable with local assets and an offline shell',async({playwright,baseURL},testInfo)=>{
 const context=await playwright.chromium.launchPersistentContext(testInfo.outputPath('install-profile'),{headless:true,...(process.platform==='win32'?{channel:'msedge'}:{}),args:['--disable-gpu','--renderer-process-limit=2']});try{const page=await context.newPage();await page.goto(baseURL);await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));});const client=await context.newCDPSession(page);await client.send('Page.enable');const {data,errors}=await client.send('Page.getAppManifest');expect(errors).toEqual([]);const manifest=JSON.parse(data);expect(manifest.name).toBe('AgriSmart');expect(manifest.short_name).toBe('AgriSmart');expect(manifest.display).toBe('standalone');expect(manifest.icons).toHaveLength(2);for(const icon of manifest.icons){const response=await context.request.get(new URL(icon.src,page.url()).href);expect(response.ok()).toBe(true);}const install=await client.send('Page.getInstallabilityErrors');expect(install.installabilityErrors).toEqual([]);await context.setOffline(true);await page.reload();await expect(page.locator('header h1')).toHaveText('AgriSmart');}finally{await context.close();}
});

test('farm preferences can stay in the current session when phone storage is unavailable',async({page})=>{
 await page.addInitScript(()=>{const save=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='agrismart_farm_setup')throw new DOMException('Fictional unavailable storage','QuotaExceededError');return save.call(this,key,value);};});
 await page.goto('/');await primary(page).click();for(let step=0;step<4;step++)await primary(page).click();await expect(page.getByRole('alert')).toContainText('continue');await page.getByRole('button',{name:'Continue for now',exact:true}).click();await expect(page.locator('.tool-nav')).toBeVisible();await primary(page).click();await expect(page.locator('input[name="check-crop"]')).toHaveCount(4);await primary(page).click();await expect(page.locator('h2')).toContainText('Check maize');await expect(page.locator('.status-chip')).toHaveAccessibleName('Online');
});



