import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const nso = JSON.parse(readFileSync(new URL('../../src/locales/nso.json', import.meta.url), 'utf8'));
test('FAW opens first, handles uncertainty, clears stale advice and resets', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Check maize for Fall Armyworm early' })).toBeVisible();
  await page.getByRole('button', { name: 'See next steps' }).click();
  await expect(page.getByRole('alert')).toContainText('Answer each question');
  for (const key of ['windows', 'eggs', 'damage']) await page.locator(`input[name="${key}"][value="no"]`).check();
  await page.getByRole('button', { name: 'See next steps' }).click();
  await expect(page.getByRole('heading', { name: 'No signs reported — keep checking' })).toBeVisible();
  await page.locator('input[name="eggs"][value="unsure"]').check();
  await expect(page.getByRole('heading', { name: 'No signs reported — keep checking' })).toHaveCount(0);
  await page.getByRole('button', { name: 'See next steps' }).click();
  await expect(page.getByRole('heading', { name: 'Uncertain — inspect again with an adviser' })).toBeVisible();
  await page.getByRole('button', { name: 'Start again' }).click();
  await expect(page.locator('input:checked')).toHaveCount(0);
});
test('Sepedi FAW library works after cold offline reload on a phone', async ({ page, context }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto('/');
  await page.evaluate(async () => { await navigator.serviceWorker.ready; if (!navigator.serviceWorker.controller) await new Promise(resolve => navigator.serviceWorker.addEventListener('controllerchange', resolve, { once: true })); });
  await page.locator('header select').selectOption('nso');
  await context.setOffline(true);
  await page.reload();
  await expect(page.getByRole('heading', { name: nso.faw_title })).toBeVisible();
  for (const key of ['windows', 'eggs', 'damage']) await page.locator(`input[name="${key}"][value="yes"]`).check();
  await page.getByRole('button', { name: nso.faw_submit }).click();
  await expect(page.getByRole('heading', { name: nso.faw_possible })).toBeVisible();
  await expect(page.getByText(nso.faw_remove)).toBeVisible();
  await expect(page.getByText(nso.faw_chemical)).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/faw-sepedi-offline.png', fullPage: true });
});
