import { test, expect } from './helpers/fixtures';
import { readFileSync } from 'node:fs';
import { primary } from './helpers/calculator';
import { completeOnboarding } from './helpers/logbook';
for(const language of ['nso','ts','ve']){
 const messages=JSON.parse(readFileSync(new URL(`../../src/locales/${language}.json`,import.meta.url),'utf8'));
 test(`${language} switches the full interface offline and survives reopening`,async({page,context})=>{
  await page.setViewportSize({width:375,height:812});const requests=[];page.on('request',request=>{if(/translate\.google|translation\.googleapis|api\.cognitive/.test(request.url()))requests.push(request.url());});await page.goto('/');await completeOnboarding(page);await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));});await context.setOffline(true);await page.locator('header select').selectOption(language);await expect(page.locator('html')).toHaveAttribute('lang',language);await page.locator('.tool-nav button').nth(1).click();await primary(page).click();await expect(page.locator('#crop-maize').locator('..')).toContainText(messages.crop_maize);await primary(page).click();await primary(page).click();await page.locator('#area').fill('0');await primary(page).click();await expect(page.getByRole('alert')).toContainText(messages['Enter a field size of at least 0.01 hectares. For example, enter 2 for two hectares.']);await page.reload();await expect(page.locator('html')).toHaveAttribute('lang',language);await page.locator('.tool-nav button').nth(2).click();await expect(page.getByText(messages['Your records are protected'],{exact:true})).toBeVisible();await primary(page).click();await expect(page.getByRole('heading',{name:messages['Protect your logbook'],exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(requests).toEqual([]);await page.screenshot({path:`docs/ui/phase4/language-${language}.png`});
 });
}
test('a legacy Sepedi preference migrates rather than becoming Northern Sami',async({page})=>{await page.goto('/');await page.evaluate(()=>localStorage.setItem('agripulse_lang','se'));await page.reload();await expect(page.locator('header select')).toHaveValue('nso');await expect(page.locator('html')).toHaveAttribute('lang','nso');});
