import { test, expect } from '@playwright/test';
import { primary, back, assertSafeActions } from './helpers/calculator';
const sizes=[[360,640],[390,844],[768,1024],[1366,768],[360,320],[640,360]];
for(const [width,height] of sizes) for(const mode of ['english','pseudo','large-text']) test(`phase 3 ${width}x${height} ${mode}`,async({page})=>{
 await page.setViewportSize({width,height}); await page.goto(mode==='pseudo'?'/?pseudo=1':'/');
 if(await page.locator('.language-picker').count()) await primary(page).click();
 if(mode==='large-text') await page.evaluate(()=>document.documentElement.style.fontSize='200%');
 const snap=async name=>{await assertSafeActions(page);if(width===360||width===1366)await page.screenshot({path:`docs/ui/phase3/${width}x${height}-${mode}-${name}.png`});};
 await primary(page).click();await snap('diagnose-intro');await primary(page).click();
 await primary(page).click();await expect(page.getByRole('alert')).toBeVisible();
 for(let i=0;i<3;i++){await page.locator('input[value="yes"]').check();await snap(`question-${i+1}`);await primary(page).click();}
 await snap('diagnosis-result');await primary(page).click();
 for(let i=0;i<6;i++){await snap(`management-${i+1}`);await primary(page).click();}
 await back(page).click();await page.locator('.tool-nav button').nth(2).click();await snap('logbook-locked');await primary(page).click();
 await page.getByLabel(/^Encryption passphrase/).fill('fictional test passphrase');await page.getByLabel(/^Confirm new passphrase/).fill('fictional test passphrase');await snap('protection');await primary(page).click();
 await expect(page.locator('.tool-nav')).toBeVisible();await expect(page.getByLabel(/^Encryption passphrase/)).toHaveCount(0);await snap('logbook-home');
 for(let i=0;i<6;i++){await primary(page).click();await page.getByLabel(/^Activity/).fill(`Fictional planting ${i}`);await snap('entry-activity');await primary(page).click();await page.getByLabel(/^Notes/).fill('Fictional field observation');await snap('entry-notes');await primary(page).click();await expect(page.locator('input[type="checkbox"]')).toBeChecked();await snap('entry-review');await primary(page).click();await snap('entry-saved');await primary(page).click();await expect(page.locator('.tool-nav')).toBeVisible();}
 await expect(page.locator('article')).toHaveCount(3);await snap('recent-entries');await page.getByRole('button',{name:/All entries/}).click();await expect(page.locator('article')).toHaveCount(height<700?3:5);await snap('all-entries');await page.getByRole('button',{name:/Next page/}).click();await expect(page.locator('article')).toHaveCount(height<700?3:1);await primary(page).click();
 await page.locator('article button').first().click();await snap('entry-detail');await primary(page).click();await expect(page.getByLabel(/^Activity/)).toHaveValue('Fictional planting 5');await back(page).click();
});

test('phase 3 cold offline records, settings, encrypted backup and lock',async({page,context})=>{
 await page.goto('/');await primary(page).click();await page.locator('.tool-nav button').nth(2).click();await primary(page).click();
 await page.getByLabel('Encryption passphrase',{exact:true}).fill('fictional offline passphrase');await page.getByLabel('Confirm new passphrase').fill('fictional offline passphrase');await primary(page).click();await expect(page.locator('.tool-nav')).toBeVisible();
 await primary(page).click();await page.getByLabel('Activity',{exact:true}).fill('Fictional offline planting');await primary(page).click();await page.getByLabel('Notes',{exact:true}).fill('Fictional private observation');await primary(page).click();await primary(page).click();await primary(page).click();
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));});
 await context.setOffline(true);await page.reload();await page.locator('.tool-nav button').nth(2).click();await primary(page).click();await page.getByLabel('Encryption passphrase',{exact:true}).fill('wrong fictional passphrase');await primary(page).click();await expect(page.getByRole('alert')).toBeVisible();await page.getByLabel('Encryption passphrase',{exact:true}).fill('fictional offline passphrase');await primary(page).click();
 await expect(page.locator('article')).toContainText('Fictional offline planting');await page.locator('article button').click();await expect(page.locator('article')).toContainText('Fictional private observation');await back(page).click();
 await page.getByRole('button',{name:'Record settings',exact:true}).click();await assertSafeActions(page);await page.getByRole('button',{name:'Backup and restore',exact:true}).click();const download=page.waitForEvent('download');await primary(page).click();expect((await download).suggestedFilename()).toBe('agripulse-encrypted-backup.json');await back(page).click();await primary(page).click();await expect(page.locator('article')).toHaveCount(0);await expect(page.locator('.tool-nav')).toBeVisible();
});
import { unlockVault, encrypt, decrypt } from '../../src/security/crypto.js';
test('phase 3 opted-in sync, reviewed conflict and explicit phone resolution',async({page,context})=>{
 const passphrase='fictional conflict passphrase';
 await page.goto('/');await primary(page).click();await page.locator('.tool-nav button').nth(2).click();await primary(page).click();await page.getByLabel('Encryption passphrase',{exact:true}).fill(passphrase);await page.getByLabel('Confirm new passphrase').fill(passphrase);await primary(page).click();await expect(page.locator('.tool-nav')).toBeVisible();
 await page.getByRole('button',{name:'Record settings',exact:true}).click();await page.getByRole('button',{name:'Optional cloud account',exact:true}).click();await page.getByRole('button',{name:'Create a cloud account',exact:true}).click();
 await page.getByLabel('Encryption passphrase',{exact:true}).fill(passphrase);await page.getByLabel('Email',{exact:true}).fill('phase3-'+crypto.randomUUID()+'@example.com');await page.getByLabel('Account password (at least 12 characters)',{exact:true}).fill('different fictional password');await assertSafeActions(page);await primary(page).click();await expect(page.getByText('Signed in. Only records you choose to share will upload.',{exact:true})).toBeVisible();await back(page).click();await back(page).click();await back(page).click();
 await primary(page).click();await page.getByLabel('Activity',{exact:true}).fill('Fictional shared planting');await primary(page).click();await page.getByLabel('Notes',{exact:true}).fill('Fictional starting observation');await primary(page).click();await page.getByRole('checkbox',{name:'Keep my records on this phone only',exact:true}).uncheck();await primary(page).click();await primary(page).click();await expect(page.locator('article')).toContainText('Synced');
 const snapshot=await(await context.request.get('/api/v1/me/export')).json();const record=snapshot.records[0];const key=await unlockVault(passphrase,snapshot.vault);
 await context.setOffline(true);await page.locator('article button').click();await primary(page).click();await page.getByLabel('Activity',{exact:true}).fill('Fictional merged planting');await primary(page).click();await page.getByLabel('Notes',{exact:true}).fill('Fictional merged observation');await primary(page).click();await primary(page).click();await primary(page).click();
 const remote=await context.request.post('/api/v1/sync',{headers:{'X-AgriPulse-Request':'1'},data:{mutationId:crypto.randomUUID(),recordId:record.id,vaultId:snapshot.vault.id,sharing:'cloud',baseVersion:record.version,operation:'upsert',envelope:await encrypt(key,snapshot.vault.id,record.id,{activity:'Fictional remote harvest',notes:'Fictional other device observation',category:'harvest',createdAt:100})}});expect(remote.status()).toBe(200);await context.setOffline(false);
 await page.getByRole('button',{name:/Review cloud copy/}).click({timeout:30000});await assertSafeActions(page);await primary(page).click();await expect(page.getByText('Fictional remote harvest',{exact:true})).toBeVisible();await expect(page.getByText('Fictional other device observation',{exact:true})).toBeVisible();await page.getByRole('radio',{name:'Keep current phone version',exact:true}).check();await assertSafeActions(page);await page.screenshot({path:'docs/ui/phase3/conflict-review.png'});page.once('dialog',dialog=>dialog.accept());await primary(page).click();await expect(page.locator('article')).toContainText('Synced');
 const final=await(await context.request.get('/api/v1/me/export')).json();expect(final.records[0].version).toBe(3);expect((await decrypt(key,snapshot.vault.id,record.id,final.records[0].envelope)).notes).toBe('Fictional merged observation');expect(JSON.stringify(final)).not.toContain('Fictional merged observation');
});

test('phase 3 diagnosis clears stale results and supplementary reference stays offline',async({page,context})=>{
 await page.goto('/');await primary(page).click();await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));});await context.setOffline(true);await page.reload();await primary(page).click();await primary(page).click();
 for(let i=0;i<3;i++){await page.locator('input[value="no"]').check();await primary(page).click();}await expect(page.locator('h2')).toHaveText('No signs reported — keep checking');await back(page).click();await page.locator('input[value="unsure"]').check();await primary(page).click();await expect(page.locator('h2')).toHaveText('Uncertain — inspect again with an adviser');await expect(page.getByText('No signs reported — keep checking',{exact:true})).toHaveCount(0);await primary(page).click();await back(page).click();await expect(page.locator('h2')).toHaveText('Uncertain — inspect again with an adviser');
 for(let i=0;i<4;i++)await back(page).click();await page.getByRole('button',{name:'Offline reference',exact:true}).click();await primary(page).click();await expect(page.locator('input[name="symptom"]')).toHaveCount(2);await page.locator('input[name="symptom"]').first().check();await primary(page).click();await assertSafeActions(page);await primary(page).click();await assertSafeActions(page);await primary(page).click();await assertSafeActions(page);await primary(page).click();await expect(page.locator('input[name="symptom"]:checked')).toHaveCount(0);
});

test('phase 3 delete confirmation restores focus and keeps actions reachable with large text',async({page})=>{
 await page.setViewportSize({width:360,height:640});await page.goto('/');await primary(page).click();await page.locator('.tool-nav button').nth(2).click();await primary(page).click();await page.getByLabel('Encryption passphrase',{exact:true}).fill('fictional delete passphrase');await page.getByLabel('Confirm new passphrase').fill('fictional delete passphrase');await primary(page).click();await expect(page.locator('.tool-nav')).toBeVisible();await primary(page).click();await page.getByLabel('Activity',{exact:true}).fill('Fictional deletion check');await primary(page).click();await primary(page).click();await primary(page).click();await primary(page).click();await page.locator('article button').click();
 await page.setViewportSize({width:360,height:320});await page.evaluate(()=>document.documentElement.style.fontSize='200%');const trigger=page.getByRole('button',{name:'Delete entry',exact:true});await trigger.click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await expect.poll(() => dialog.locator('.min-h-0').evaluate(body => body.clientHeight > 0)).toBe(true);await expect.poll(()=>dialog.locator('button').evaluateAll(buttons=>buttons.every(button=>{const r=button.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth;}))).toBe(true);await page.screenshot({path:'docs/ui/phase3/delete-large-text.png'});await page.keyboard.press('Escape');await expect(trigger).toBeFocused();await trigger.click();await dialog.getByRole('button',{name:'Delete entry',exact:true}).click();await expect(page.locator('.tool-nav')).toBeVisible();await expect(page.locator('article')).toHaveCount(0);
});
