import { screenshot } from './helpers/screenshot';
import { test, expect } from '@playwright/test';
import { unlockVault, encrypt } from '../../src/security/crypto.js';
import { primary, back, assertSafeActions } from './helpers/calculator';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
const passphrase='fictional gallery passphrase';
for(const [width,height] of [[360,640],[1366,768]])for(const mode of ['english','pseudo','large-text']){
 test(`phase 4 gallery ${width}x${height} ${mode}`,async({page,context,browser},testInfo)=>{
  test.setTimeout(150000);await page.setViewportSize({width,height});
  await page.addInitScript(()=>{
   const store=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(window.profileStorageFault&&key==='agrismart_farm_setup')throw new DOMException('Fictional profile storage failure','QuotaExceededError');return store.call(this,key,value);};
   const tx=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(stores,...args){if(window.storageFault&&Array.from(typeof stores==='string'?[stores]:stores).some(name=>['encryptedLogs','mutations'].includes(name)))throw new DOMException('Fictional storage failure','QuotaExceededError');return tx.call(this,stores,...args);};
   const all=IDBObjectStore.prototype.getAll;IDBObjectStore.prototype.getAll=function(...args){const request=all.apply(this,args);if(this.name==='encryptedLogs'||this.name==='mutations'){const descriptor=Object.getOwnPropertyDescriptor(IDBRequest.prototype,'onsuccess');let callback;Object.defineProperty(request,'onsuccess',{configurable:true,get:()=>callback,set(handler){callback=handler;descriptor.set.call(request,event=>{if(window.holdRecords)(window.recordReads??=[]).push(()=>handler(event));else handler(event);});}});}return request;};
   window.releaseRecords=()=>{window.holdRecords=false;for(const finish of window.recordReads||[])finish();window.recordReads=[];};
   const encrypt=SubtleCrypto.prototype.encrypt;SubtleCrypto.prototype.encrypt=async function(...args){const result=await encrypt.apply(this,args);if(window.holdEncrypt)await new Promise(resolve=>{window.releaseEncrypt=()=>{window.holdEncrypt=false;resolve();};});return result;};
  });
  const folder=`docs/ui/phase4/${width}x${height}-${mode}`;mkdirSync(folder,{recursive:true});const states=[];
  const snap=async name=>{if(name.includes('error') && await page.locator('main [role="alert"]').count())await page.locator('main [role="alert"]').first().scrollIntoViewIfNeeded();if(await page.getByRole('dialog').count()){await expect.poll(()=>page.getByRole('dialog').locator('button').evaluateAll(buttons=>buttons.every(button=>{const box=button.getBoundingClientRect();return box.top>=0&&box.bottom<=innerHeight&&box.left>=0&&box.right<=innerWidth;}))).toBe(true);}else await assertSafeActions(page);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth)).toBe(true);await screenshot(page,{path:`${folder}/${name}.png`});states.push(name);};
  const scroll=async()=>page.locator('.wizard-content').evaluate(element=>element.scrollTo({top:element.scrollHeight}));
  await page.goto(mode==='pseudo'?'/?pseudo=1':'/');if(mode==='large-text')await page.evaluate(()=>document.documentElement.style.fontSize='200%');await expect(page.locator('header h1')).toContainText('AgriSmart');await expect(page).toHaveTitle('AgriSmart');await snap('language');await primary(page).click();
  await snap('farm-about');await primary(page).click();await page.locator('input[value="maize"]').uncheck();await primary(page).click();await expect(page.getByRole('alert')).toBeVisible();await snap('farm-crop-error');for(const crop of ['maize','tomato','beans','cabbage'])await page.locator(`input[value="${crop}"]`).check();await snap('farm-crops');await primary(page).click();await page.locator('.farm-setup input').fill('-1');await primary(page).click();await snap('farm-size-error');await page.locator('.farm-setup input').fill('2.5');await snap('farm-size');await primary(page).click();await snap('farm-review');await page.evaluate(()=>window.profileStorageFault=true);await primary(page).click();await expect(page.getByRole('alert')).toBeVisible();await snap('farm-storage-error');await page.evaluate(()=>window.profileStorageFault=false);await primary(page).click();await expect(page.locator('.tool-nav')).toBeVisible();await snap('crop-home');await expect(page.locator('.tool-home .home-icon')).toHaveCount(0);
  await primary(page).click();await snap('crop-choice');await primary(page).click();await snap('maize-intro');await primary(page).click();await primary(page).click();await snap('maize-answer-error');for(let i=0;i<3;i++){await page.locator('input[value="yes"]').check();await snap(`maize-question-${i+1}`);await primary(page).click();}await expect(page.locator('.guidance-list')).toContainText('remove and crush');await snap('maize-result');await scroll();await snap('maize-result-guidance');await primary(page).click();for(let i=0;i<6;i++){await snap(`maize-management-${i+1}`);await primary(page).click();}
  await page.getByRole('button',{name:/Offline reference/}).click();await snap('reference');await primary(page).click();await snap('other-symptom-choice');await page.locator('input[name="symptom"]').first().check();for(let i=0;i<3;i++){await primary(page).click();await snap(`other-symptom-${i+1}`);}await primary(page).click();await back(page).click();await back(page).click();await back(page).click();
  for(const crop of ['tomato','beans','cabbage']){
   await page.locator(`input[name="check-crop"][value="${crop}"]`).check();await primary(page).click();await snap(`${crop}-intro`);await primary(page).click();for(let i=0;i<3;i++){await page.locator('input[value="yes"]').check();await snap(`${crop}-question-${i+1}`);await primary(page).click();}await expect(page.locator('.guidance-list')).toHaveCount(1);await snap(`${crop}-result`);await scroll();await snap(`${crop}-guidance`);await primary(page).click();
  }
  await back(page).click();await page.locator('.tool-nav button').nth(1).click();await snap('calculator-home');await primary(page).click();await snap('calculator-crop');await primary(page).click();await snap('calculator-product');await primary(page).click();await page.locator('#area').fill('0');await primary(page).click();await snap('calculator-error');await page.locator('#area').fill('2');await snap('calculator-area');await primary(page).click();await snap('calculator-review');await primary(page).click();await snap('calculator-result');await scroll();await snap('calculator-result-details');await primary(page).click();await back(page).click();
  await page.evaluate(()=>window.holdRecords=true);await page.locator('.tool-nav button').nth(2).click();await expect(primary(page)).toBeDisabled();await snap('records-loading');await page.evaluate(()=>window.releaseRecords());await expect(primary(page)).toBeEnabled();await snap('records-locked');
  await page.locator('.tool-nav button').nth(1).click();await page.evaluate(()=>window.storageFault=true);await page.locator('.tool-nav button').nth(2).click();await expect(page.getByRole('alert')).toBeVisible();await snap('records-storage-error');await page.evaluate(()=>window.storageFault=false);await page.getByRole('button',{name:/Reload records/}).click();await primary(page).click();await snap('records-protection');await page.getByLabel(/^Encryption passphrase/).fill(passphrase);await page.getByLabel(/^Confirm new passphrase/).fill('different fictional phrase');await primary(page).click();await snap('records-passphrase-error');await page.getByLabel(/^Confirm new passphrase/).fill(passphrase);await primary(page).click();await expect(page.locator('.tool-nav')).toBeVisible();await snap('records-empty');
  await primary(page).click();await primary(page).click();await snap('entry-activity-error');await page.getByLabel(/^Activity/).fill('Fictional field inspection');await snap('entry-activity');await primary(page).click();await page.getByLabel(/^Notes/).fill('Fictional observations only');await snap('entry-notes');await primary(page).click();await snap('entry-review-local');await page.evaluate(()=>window.storageFault=true);await primary(page).click();await expect(page.getByRole('alert')).toBeVisible();await snap('entry-save-error');await page.evaluate(()=>{window.storageFault=false;window.holdEncrypt=true;});await primary(page).click();await expect(primary(page)).toBeDisabled();await snap('entry-saving');await page.evaluate(()=>window.releaseEncrypt());await expect(page.locator('h2')).toContainText('Entry saved');await snap('entry-saved');await primary(page).click();await expect(page.locator('.tool-nav')).toBeVisible();await snap('records-recent');await page.getByRole('button',{name:/All entries/}).click();await snap('records-all');await primary(page).click();await page.locator('article button').click();await snap('entry-details');await page.getByRole('button',{name:/Delete entry/}).click();await snap('entry-delete');await page.keyboard.press('Escape');await primary(page).click();await snap('entry-edit');await back(page).click();
  await page.getByRole('button',{name:/Record settings/}).click();await snap('record-settings');await page.getByRole('button',{name:/Backup and restore/}).click();await snap('encrypted-backup');const downloadPromise=page.waitForEvent('download');await primary(page).click();const download=await downloadPromise;const backup=readFileSync(await download.path());await back(page).click();await page.getByRole('button',{name:/Optional cloud account/}).click();await snap('account-sign-in');await page.getByRole('button',{name:/Create a cloud account/}).click();await snap('account-register');await page.getByLabel(/^Encryption passphrase/).fill(passphrase);await page.getByLabel(/^Email/).fill(`gallery-${crypto.randomUUID()}@example.com`);await page.getByLabel(/^Account password/).fill('different fictional password');await primary(page).click();await expect(page.getByText(/^Signed in\./)).toBeVisible();await snap('account-signed-in');await back(page).click();await back(page).click();await back(page).click();
  await primary(page).click();await page.getByLabel(/^Activity/).fill('Fictional shared inspection');await primary(page).click();await primary(page).click();await page.locator('input[type="checkbox"]').uncheck();await snap('entry-review-shared');await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await context.setOffline(true);await primary(page).click();await primary(page).click();await page.locator('.status-chip').click();await snap('offline-pending');await page.keyboard.press('Escape');await context.setOffline(false);await expect(page.locator('article').filter({hasText:'Fictional shared inspection'})).toContainText('Synced',{timeout:30000});await page.locator('.status-chip').click();await snap('synced');await page.keyboard.press('Escape');
  const snapshot=await(await context.request.get('/api/v1/me/export')).json();const record=snapshot.records.find(row=>!row.deleted);const key=await unlockVault(passphrase,snapshot.vault);await context.setOffline(true);await page.locator('article').filter({hasText:'Fictional shared inspection'}).locator('button').click();await primary(page).click();await page.getByLabel(/^Activity/).fill('Fictional merged inspection');await primary(page).click();await page.getByLabel(/^Notes/).fill('Fictional merged observation');await primary(page).click();await primary(page).click();await primary(page).click();const remote=await context.request.post('/api/v1/sync',{headers:{'X-AgriPulse-Request':'1'},data:{mutationId:crypto.randomUUID(),recordId:record.id,vaultId:snapshot.vault.id,sharing:'cloud',baseVersion:record.version,operation:'upsert',envelope:await encrypt(key,snapshot.vault.id,record.id,{activity:'Fictional remote inspection',notes:'Fictional remote observation',category:'pest_control',createdAt:100})}});expect(remote.status()).toBe(200);await context.setOffline(false);await page.getByRole('button',{name:/Review cloud copy/}).click({timeout:30000});await snap('conflict-phone');await primary(page).click();await snap('conflict-cloud');await page.getByRole('radio',{name:/Keep current phone version/}).check();page.once('dialog',dialog=>dialog.accept());await primary(page).click();await expect(page.locator('article').filter({hasText:'Fictional merged inspection'})).toContainText('Synced',{timeout:30000});await snap('conflict-resolved');
  let release;const gate=new Promise(resolve=>release=resolve);await page.route('**/api/v1/me',async route=>{await gate;await route.continue();});await page.locator('.status-chip').click();await page.getByRole('dialog').locator('.ui-primary').click();await expect(page.getByRole('dialog').locator('.ui-primary')).toBeDisabled();await snap('syncing');release();await expect(page.getByRole('dialog').locator('.ui-primary')).toBeEnabled();await page.unroute('**/api/v1/me');await page.keyboard.press('Escape');
  await page.route('**/api/v1/me',route=>route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({error:'Fictional expired session'})}));await page.locator('.status-chip').click();await page.getByRole('dialog').locator('.ui-primary').click();await expect(page.getByRole('dialog')).toContainText(/Session expired/);await snap('sync-error');await page.unroute('**/api/v1/me');await page.keyboard.press('Escape');
  await page.getByRole('button',{name:/Record settings/}).click();await page.getByRole('button',{name:/Account controls/}).click();await snap('account-tools');await page.getByRole('button',{name:/Export readable cloud data/}).click();await snap('readable-export');await back(page).click();await page.getByRole('button',{name:/Delete cloud account/}).click();await snap('account-deletion');await back(page).click();await primary(page).click();await expect(page.getByText(/^Signed out\./)).toBeVisible();await snap('account-signed-out');await back(page).click();
  const restored=await browser.newContext({viewport:{width,height}});const other=await restored.newPage();await other.goto(new URL(mode==='pseudo'?'/?pseudo=1':'/',page.url()).href);await other.evaluate(()=>{localStorage.setItem('agripulse_lang','en');localStorage.setItem('agrismart_farm_setup',JSON.stringify({version:1,crops:['maize'],name:'',community:'',area:''}));});await other.reload();if(mode==='large-text')await other.evaluate(()=>document.documentElement.style.fontSize='200%');await other.locator('.tool-nav button').nth(2).click();await primary(other).click();await other.getByRole('button',{name:/Restore my records/}).click();await assertSafeActions(other);await screenshot(other,{path:`${folder}/restore-form.png`});await other.getByLabel(/^Encryption passphrase/).fill(passphrase);await other.locator('input[type="file"]').setInputFiles({name:'fictional-backup.json',mimeType:'application/json',buffer:backup});await primary(other).click();await expect(other.getByText(/^Records restored on this phone./)).toBeVisible();await assertSafeActions(other);await screenshot(other,{path:`${folder}/restore-complete.png`});states.push('restore-form','restore-complete');await restored.close();
  writeFileSync(`${folder}/states.json`,JSON.stringify({viewport:{width,height},mode,states},null,2));testInfo.annotations.push({type:'screenshots',description:`${states.length} states in ${folder}`});
 });
}

